### ISSUE TITLE
RecordFormat macro for List - diverging implicit expansion for type 

### ISSUE THREAD

**Issue by vilinski** [sksamuel/avro4s#234] opened 2018-10-10 15:05 UTC
avro4s 2.0.1
scala 2.12.7

the following code doesn't work for me

```scala
import com.sksamuel.avro4s._
object Formats {
    case class TestEntry(name: String)
    case class Test(id: Int, entries: List[TestEntry])
    val test: RecordFormat[Test] = RecordFormat[Test] // <---
}
```

however if `entries` is a `List[Int]` it compiles. Do I something wrong?

**Comment by sksamuel** [comment] 2018-10-10 20:37
I added a test with the classes you've pasted here and it works ok for me.
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue234.scala

Can you make a test that shows this - perhaps add one to this code base and PR it back as a failing test?

**Comment by sksamuel** [comment] 2018-10-12 11:09
-XLog-implicits is a bit hard to understand for sure.

The only issue I know of at the moment is a sequence of maps of case classes. Are you mixing maps in your real code rather than the example?

**Comment by vilinski** [comment] 2018-10-12 12:45
I have no `Map`s from which I'm aware. One of case classes has `BsonValue` field, and `BsonDocument` implements `java.util.Map<String, BsonValue>`. But it's not a class which brings compile errors and where I have custom serializer:

```scala
  implicit object BsonValueToSchema extends SchemaFor[BsonValue] {
    override val schema: Schema = Schema.create(Schema.Type.STRING)
  }
  implicit object BsonValueFromValue extends Decoder[BsonValue] {
    override def decode(value: Any, schema: Schema): BsonValue = value match {
      case s: CharSequence => BsonDocument(s.toString).get("value")
      case other           => sys.error("Unsupported type for BsonValue " + other)
    }
  }
  implicit object BsonValueToValue extends Encoder[BsonValue] {
    override def encode(value: BsonValue, schema: Schema): String = Document("value" -> value).toJson()
  }
```

I have also some ADT where each case gets `RecordFormat` compiled, but a case class containing a trait not. Don't get why. 
I would also mention, anything works with 1.8.3, but not with 2.0.1. Is there anywhere a changelog?
By the way, could it be possible to support sealed class as ADTs additionally to traits?

**Comment by sksamuel** [comment] 2018-10-12 13:19
If shapeless supports coproducts on sealed classes then yes, but I don't know if it does. Just try it in avro4s, if it works then you're good.

Any diverging implicit expansion errors are because there's an error in the macro, or the macro doesn't support something, and so it goes around in a circle trying to find a match and then gives up.

If you want to paste the log from log-implicits it won't hurt.

**Comment by vilinski** [comment] 2018-10-15 12:17
This doesn't compile

```scala
  final case class TestEntry(name: String)
  sealed trait TestTrait
  sealed class TestClass extends TestTrait
  final case class Test(id: Int, entries: List[TestEntry]) extends TestClass
  final case class ContainsTestTrait(testTrait: TestTrait)
  val format: RecordFormat[ContainsTestTrait] = RecordFormat[ContainsTestTrait]
```

**Comment by sksamuel** [comment] 2018-10-15 12:35
Yes that fails for me too.

**Comment by sksamuel** [comment] 2018-10-16 08:03
Ok so I think the issue is that the ADT hierarchy in this example is this:

TestTrait 
  |
TestClass
  |
Test

And both `TestClass` and `Test` are concrete children of `TestTrait`, so Shapeless provides them both as part of the `Coproduct`, but `TestClass` is an empty class so what can we do with it (the macro rejects it because its not a case class).

**Comment by vilinski** [comment] 2018-10-17 20:42
Thank you for investigation! 
Found some other case. This code compiles only if Test has lists. Otherwise `diverging implicit expansion...`, regardless whether parent is class or trait.

```scala
case class TestEntry(name: String)
sealed trait TestClass
final case class Test(id: Int, entries: TestEntry) extends TestClass
// final case class Test(id: Int, entries: List[TestEntry]) extends TestClass
case class ContainsTestClass(testTrait: TestClass)
// case class ContainsTestClass(testTrait: List[TestClass]) // <-- this list works however

val format: RecordFormat[ContainsTestClass] = RecordFormat[ContainsTestClass] 
```

**Comment by sksamuel** [comment] 2018-10-17 20:56
I'm confused by your latest post as the bit that works is commented out? Can you clean it up so it's just what works or what fails? Thanks.

**Comment by sksamuel** [comment] 2018-10-18 12:43
Thanks for the updated examples.

**Comment by sksamuel** [comment] 2018-11-26 05:47
I have had a good play with this and cannot solve it.

I've narrowed the test case down to this:

```scala
sealed trait TestClass
case class Test(entries: Option[String]) extends TestClass
case class ContainsTestClass(testClass: TestClass)
val decoder: Decoder[ContainsTestClass] = Decoder[ContainsTestClass]
```

Note that it fails for `Option[String]`, `List[String]`, `Array[Int]` and so on. I think it fails whenever the field of Test is a type that has a type parameter as it works for basic types like String and UUID.

When we have a trait, we use shapeless to extract a `Coproduct` to handle the trait subtypes. Perhaps the mechanism it uses isn't incompatible with the way macros are handled in avro4s in some subtle way.

**Comment by vilinski** [comment] 2018-11-26 22:44
a pity... probably we'll keep 1.8.3 forever :-/

**Comment by sksamuel** [comment] 2018-12-02 09:35
Looks like it's fixed now. I've got your examples working in 2.0.3 so please try that version.

**Closed by sksamuel** 2018-12-02 09:35 UTC

**Comment by vlfig** [comment] 2018-12-12 17:49
The following

```scala
package com.sksamuel.avro4s.github

import com.sksamuel.avro4s.{AvroSchema, Decoder, Encoder}
import org.scalatest.{FunSuite, Matchers}

sealed trait M
case class Ma(qs: N) extends M
// doesn't need to be unique

sealed trait N
case class N1() extends N
case class N2() extends N
// cannot be unique


// ================= using case objects works: =============

sealed trait J
case class Ja(qs: K) extends J
sealed trait K
case object K1 extends K
case object K2 extends K


class GithubIssue255 extends FunSuite with Matchers {
  test("union of union ") {
    AvroSchema[J]
       Encoder[J]
       Decoder[J]
    AvroSchema[M]
       Encoder[M]
       Decoder[M]
  }
}
```

fails with 

```
[error] /home/vlfig/projects/avro4s/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue255.scala:30: diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[com.sksamuel.avro4s.github.M]
[error] starting with macro method applyMacro in object SchemaFor
[error] Error occurred in an application involving default arguments.
[error]     AvroSchema[M]
[error]               ^
[error] /home/vlfig/projects/avro4s/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue255.scala:31: diverging implicit expansion for type com.sksamuel.avro4s.Encoder[com.sksamuel.avro4s.github.M]
[error] starting with macro method applyMacro in object Encoder
[error] Error occurred in an application involving default arguments.
[error]        Encoder[M]
[error]               ^
[error] /home/vlfig/projects/avro4s/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue255.scala:32: diverging implicit expansion for type com.sksamuel.avro4s.Decoder[com.sksamuel.avro4s.github.M]
[error] starting with macro method applyMacro in object Decoder
[error] Error occurred in an application involving default arguments.
[error]        Decoder[M]
[error]               ^
```

Happy to file a different issue but it looks like the same one.
