### ISSUE TITLE
Diverging implicit expansion for SchemaFor in Coproducts inside case classes

### ISSUE THREAD

**Issue by fedefernandez** [sksamuel/avro4s#273] opened 2019-01-22 17:17 UTC
Hi @sksamuel, just found this while upgrading one project from `1.8.3` to `2.0.2` but seems its also reproducible in master.

Given this model:
```scala
case class Coproducts(cp: Int :+: String :+: Boolean :+: CNil)
case class CoproductOfCoproductsField(cp: Coproducts :+: Boolean :+: CNil)
```

Trying to get a `SchemaFor[CoproductOfCoproductsField]` gives you a diverging implicit error:
```
diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[com.sksamuel.avro4s.schema.CoproductOfCoproductsField]
```

You can see it here in action

https://github.com/sksamuel/avro4s/compare/master...fedefernandez:ff/coproducts-in-fields?expand=1

Do you know why this could be happen? Thanks

**Comment by Schm1tz1** [comment] 2019-01-23 12:03
Hi @fedefernandez and @sksamuel,

I'm facing the sami issue in 2.0.2 on scala 2.11. I have a (nested) class that is used to store tree-like data structured which looks like the following:
```
import com.sksamuel.avro4s.{AvroSchema, SchemaFor}
import shapeless.{:+:, CNil}

case class DataWrapper(name: String,
                       dataType: String,
                       value: Option[String :+: Long :+: Double :+: CNil],
                       children: Option[List[DataWrapper]]
                      )


object AvroTest extends App {

  implicit val schemaFor = SchemaFor[DataWrapper]
  val newSchema = AvroSchema[DataWrapper]

  println(newSchema.toString(true))

}
```
This results in the same error:

> AvroTest.scala:13: error: diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[DataWrapper]
> starting with method optionSchemaFor in object SchemaFor
>   implicit val schemaFor = SchemaFor[DataWrapper]
>                                     ^
>AvroTest.scala:14: error: diverging implicit expansion for type com.sksamuel.avro4s.SchemaFor[DataWrapper]
> starting with method optionSchemaFor in object SchemaFor
>   val newSchema = AvroSchema[DataWrapper]

I have tried with the simple nested example from the README:
```
case class Recursive(payload: Int, next: Option[Recursive])

implicit val schemaFor = SchemaFor[Recursive]
val newSchema = AvroSchema[Recursive]
```

This leads to the same error. Any ideas/suggestions?

**Comment by sksamuel** [comment] 2019-01-28 20:00
It happens on some cases, and sometimes on recursion.
The problem is, I don't know how to fix it.

**Comment by choedl** [comment] 2019-02-11 09:18
This also happens sometimes with enumerations.
This works:
```
// WORKING
package test

import java.io.File

import com.sksamuel.avro4s.AvroSchema
import com.sksamuel.avro4s.AvroOutputStream

object MyProtocol2 extends App {
  trait Event {
    def id: String
  }
  final case class MyEvent1(id: String, payload: Payload1) extends Event
  final case class MyEvent2(id: String, payload: Payload2) extends Event

  case class Payload1(someid: String, myStatus: MyStatus.MyStatusVal)
  case class Payload2(someid: String, somethingelse: String, myStatus: MyStatus.MyStatusVal)

  object MyStatus extends Enumeration {
    type MyStatusVal = Value
    val Status1, Status2, Status3 = Value
  }

  val schema = AvroSchema[MyEvent1]
  val os = AvroOutputStream.data[MyEvent1].to(new File("myevent1.avro")).build(schema)
}
```
The following only works if the enumeration is moved out of the object, otherwise the diverging implicit expansion happens like above:
```
// NOT WORKING
package test

import java.io.File

import com.sksamuel.avro4s.AvroSchema
import com.sksamuel.avro4s.AvroOutputStream


object MyProtocol extends App {
  final case class MyEvent(id: String, payload: Payload)

  sealed trait Payload

  case class Payload1(someid: String, myStatus: MyStatus.MyStatusVal) extends Payload
  case class Payload2(someid: String, somethingelse: String, myStatus: MyStatus.MyStatusVal) extends Payload

  // must be defined outside of the object
  object MyStatus extends Enumeration {
    type MyStatusVal = Value
    val Status1, Status2, Status3 = Value
  }

  val schema = AvroSchema[MyEvent]
  val os = AvroOutputStream.data[MyEvent].to(new File("myevent.avro")).build(schema)
}
```

In the working case, the event classes itself extends a trait, in the not working case the payload classes extend a trait.

**Comment by klass-ivan** [comment] 2019-04-11 05:44
This is what `shapeless.Lazy` is to workarond, isn't it? The problem is that when resolving implicits compiler expect the required implicit types to be changed/reduced, but that's not the case when you've recursive implicits like when generalizing products to HList and coproducts to _ :+: CNil

**Comment by klass-ivan** [comment] 2019-04-11 11:22
I believe the issue is in `com.sksamuel.avro4s.CoproductEncoders#coproductEncoder` - the tail encoder `encoderT: Encoder[T]` should be `shaplelss.Lazy[Encoder[T]]` and usage is just `encoderT.value` in `def encode`

**Comment by sksamuel** [comment] 2019-05-18 08:40
Can you try the 3.0.x snapshot from
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s
This should be fixed and is available for 2.11 and 2.22

**Comment by ivanobulo** [comment] 2019-05-22 03:31
I believe this and #318 were caused by the same issue. My understanding is that `implicit def genCoproduct`, which is currently commented out, is conflicting with smth else.

**Comment by sksamuel** [comment] 2019-05-22 03:32
We don't need genCoproduct anymore, as that's handled by the `dispatch` method now.

**Comment by fedefernandez** [comment] 2019-05-27 08:45
@sksamuel thanks for the update. I've updated the branch and the issue seems fixed now.

https://github.com/sksamuel/avro4s/compare/master...fedefernandez:ff/coproducts-in-fields?expand=1

**Closed** 2019-05-27 18:55 UTC
Labels: bug
