### ISSUE TITLE
Enum annotations failing

### ISSUE THREAD

**Issue by fubhy** [sksamuel/avro4s#346] opened 2019-06-30 22:03 UTC
I found an issue from 2018 where the same problem is described. Apparently it has already been fixed but I am running into the issue again with 3.0-RC1: https://github.com/sksamuel/avro4s/issues/145

```
package xxx

import com.sksamuel.avro4s.{AvroName, AvroNamespace}

@AvroNamespace("com.foo")
@AvroName("MyRenamedEnum")
sealed trait MyEnum
case object FOO extends MyEnum
case object BAR extends MyEnum
```

The resulting schema doesn't have the namespace nor name that was given in the annotation.

Maybe I am doing something wrong?

**Comment by sksamuel** [comment] 2019-06-30 22:16
I would try the latest snapshot from the readme badges to ensure it hasn't been fixed. I know some enum PRs were merged just this last week.

**Comment by fubhy** [comment] 2019-07-01 01:05
Thanks for the swift reply. The latest snapshot did indeed fix another problem with enums (could not find subtype), but the namespace issue remains. I am working around it for now by placing the file in the right directory so it's not a deal breaker for me but just a little bit inconvenient.

**Comment by sksamuel** [comment] 2019-07-11 02:04
I've added tests for these and they pass so I can't see what the issue is.
If you think it's still happening please raise a PR with a failing test case.

**Closed by sksamuel** 2019-07-11 02:04 UTC
Labels: bug
